name: mFarmer
version: '1.3.5'
main: com.limitflow.mfarmer.MFarmer
api-version: '1.21'
softdepend: [WorldGuard, PlaceholderAPI, Vault, PlayerPoints]
author: Limitely

commands:
  mfarmer:
    aliases: [farmer, farm]

permissions:
  mfarmer.use:
    default: true
  mfarmer.reload:
    default: op
  mfarmer.admin:
    default: op
  mfarmer.event:
    default: op
