name: mFarmer
version: '1.2'
main: com.limitflow.mfarmer.MFarmer
api-version: '1.16'
depend: [WorldGuard, Vault]
softdepend: [PlaceholderAPI]

commands:
  mfarmer:
    usage: /mfarmer <help|salary|upgrade|reload|adminboost|giveboost>
    aliases: [farmer, farm]
permissions:
  mfarmer.use:
    description: "Для игроков, чтобы была доступна /farmer salary"
    default: true
  mfarmer.reload:
    description: "Право для перезагрузки конфига"
    default: op